set(CTEST_PROJECT_NAME "adsasd")
# SET(CTEST_SOURCE_DIRECTORY "/Users/hborcher/lua/myserver")
SET(CTEST_SOURCE_DIRECTORY "$ENV{HOME}/Dashboards/My Testing/Insight")
SET(CTEST_BINARY_DIRECTORY "$ENV{HOME}/Dashboards/My Testing/Insight-bin")
SET(CTEST_CMAKE_COMMAND "/usr/local/bin/cmake")
set(CTEST_CHECKOUT_COMMAND "git clone https://github.com/henryborchers/dummyLibraryCMakePackage.git")
#set(CTEST_CMAKE_GENERATOR "Ninja")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_USE_LAUNCHERS 1)
ctest_empty_binary_directory(${CTEST_BINARY_DIRECTORY})

ctest_start("Experimental")
ctest_configure()
#ctest_configure(BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_build()
#ctest_build(BUILD "${CTEST_BINARY_DIRECTORY}")

ctest_test()
# SET (CTEST_COMMAND "/usr/local/bin/ctest")
# SET (CTEST_COMMAND "/usr/local/bin/ctest -D Nightly")
